version: '3'

services:


    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    lrvl_mysql:
        container_name: lrvl_mysql
        image: mysql:8.1
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes:
            - lrvl_mysql_data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: lrvl_db
            MYSQL_USER: lrvl_db_user
            MYSQL_PASSWORD: lrvl_db_password
        networks:
            - mynetwork


    ####################################################################################################
    # phpmyadmin
    ####################################################################################################
    phpmyadmin:
        depends_on:
            - lrvl_mysql
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - "8082:80"
        environment:
            MYSQL_ROOT_PASSWORD: password
            PMA_HOST: lrvl_mysql
        networks:
            - mynetwork



    ####################################################################################################
    # Nginx
    ####################################################################################################
    # nginx:
    #     container_name: lrvl_nginx
    #     image: nginx
    #     ports:
    #         - 81:80
    #     volumes:
    #         - .:/var/www
    #         - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #         - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    #     depends_on:
    #         - task


    ####################################################################################################
    # task
    ####################################################################################################
    task:
        depends_on:
            - lrvl_mysql
        build:
            context: ./
            dockerfile: .docker/lrvl/Dockerfile
        container_name: task
        ports:
            - "5173:80"
        restart: unless-stopped
        working_dir: /var/www/html
        environment:
            DB_HOST: lrvl_mysql
            DB_PORT: 3306
        volumes:
            - ./:/var/www/html
            - ./.docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        networks:
            - mynetwork



    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        container_name: laravel_mailpit
        image: axllent/mailpit:latest
        ports:
        - 8026:8026
        - 1026:1026


networks:
  mynetwork:
    driver: bridge

volumes:
  lrvl_mysql_data:
